// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfvtqlacvgngyhnwcort.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmdnRxbGFjdmduZ3lobndjb3J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzA0NjMsImV4cCI6MjA1OTcwNjQ2M30.F3tZkWoMNGyvPncqy2YKt69riySGYc9Xh4EAlCsPcqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);